Добавляет разметку главной страницы
htmlacademy-adaptive/1902231-cat-energy-27 pull request #2
Opened 2022-11-28 14:41 UTC by anastasia-sp

2022-12-03 21:23 UTC, wrgraff requested changes
В целом очень хорошая работа получилась!

2022-12-03 21:23 UTC, wrgraff commented on source/index.html
> +              <a href="#">Главная</a>
Почему тут заглушка? Заглушка ставится когда мы знаем, что там будет нормальная такая обычная ссылка, но самого адреса ее мы не знаем.
Тут у нас либо ссылка на себя, либо ссылка, чья активность убрана за счет удаление атрибута `href`.

https://github.com/htmlacademy-adaptive/1902231-cat-energy-27/blob/a4875a2783d30032d60adee1ec91a89c2e0ef3da/source/index.html#L9-L11
https://github.com/htmlacademy-adaptive/1902231-cat-energy-27/blob/a4875a2783d30032d60adee1ec91a89c2e0ef3da/source/index.html#L19

2022-12-03 21:23 UTC, wrgraff commented on source/index.html
> +        <div class="main-nav__wrapper">
Можешь пояснить зачем нам на этапе разметки уже нужна тут обертка?
Необходимость обертки до начала построения сеток мы можем только предположить. Даже опытный верстальщик может их проставить с полной уверенностью далеко не всегда. Поэтому, обычно стараются ставить по минимуму, потому что добавить можно всегда, а вот удалить лишнее скорее всего забудется / будет уже некогда / прочее.

2022-12-03 21:23 UTC, wrgraff commented on source/index.html
> +      </section>
Вышло хорошо!

2022-12-03 21:23 UTC, wrgraff commented on source/index.html
> +        </ul>
Обычный список не очень хорошо сюда подходит, потому что список — это набор идентичных элементов, а тут все-таки значения парные.
Подойдет что-то вроде списка парных значений, или же лучше сделать 2 элемента, в каждом из которых парные значения будут.

2022-12-03 21:23 UTC, wrgraff commented on source/index.html
> +          <li class="example__value">60 ДНЕЙ</li>
```suggestion
          <li class="example__value">60 дней</li>
```

2022-12-03 21:23 UTC, wrgraff commented on source/index.html
> +          <button class="example__button" type="button">После</button>
Кажется, в новой версии макета кнопок никаких уже нет )
<img width="583" alt="изображение" src="https://user-images.githubusercontent.com/37917037/205461641-834675e0-7321-4512-b7b8-8a49fca912cf.png">

2022-12-03 21:23 UTC, wrgraff commented on source/index.html
> +      </div>
Зачем для каждого элемента по своей обертке О_о

2022-12-03 21:23 UTC, wrgraff commented on source/index.html
> +        <a class="main-footer__copyright copyright" href="https://htmlacademy.ru">
Получается, элемент сам в себя вложен...
Ох уж эти обертки!

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +    <title>Кэт энерджи</title>
Кажется, для внутренних страниц надо бы другие заголовки написать =)

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +              <a href="#">Главная</a>
Главная страница то есть, можно вполне рабочую ссылку на нее поставить

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +              <a href="./catalog.html">Каталог продукции</a>
Все-таки, мы ставим ссылку на себя или нет?

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +    <main class="catalog-container">
Здорово, когда идет унификация, которую ты успешно делаешь с секциями, но вот делать для каждой страницы свой контейнер — решение не очень хорошее.
Что, если у нас на сайте (а это сайт-каталог, там много страниц) будет 10-15 типов страниц? И нам надо стилистику заголовков этих самых унифицированных поменять. И будем менять 15 вместо одного =)

Ну и вообще, один из по сути трех основных блоков хэдер/мейн/футер не хочется делать отдельным. Лучше, чтобы из них из одинаковых состояли страницы как из основных самых

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +            </a>
А зачем `card-logo` в отдельный блок?
Он слишком мелкий же

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +            </h4>
Заголовок так же еще и с[сылкой должен быть](https://up.htmlacademy.ru/adaptive/27/project/cat-energy#cat-energy-6-1) же

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +        <h4 class="show-more-section__title">Показать ещё 100500 товаров</h4>
Как это 4 уровень заголовка?
Это же секция отдельная, тут как минимум 2-й получается

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +            <h4 class="card__title">
Сразу после первого уровня заголовка идет четвертый: так не бывает, они должны быть последовательны и строго соблюдать вложенность и структуру

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +          <p class="gift-section__text">Закажите все и получите чехол для кота в подарок!</p>
Почему отступ такой большой
```suggestion
        <p class="gift-section__text">Закажите все и получите чехол для кота в подарок!</p>
```

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +            <dd class="description-table__value">200 ₽</dd>
Я не уверен, что "упаковка" является термином к цене.

Если хочется заморочиться... Я делал так =)
```html
              <dl class="card-row__list">
                <dt class="visually-hidden">Объем</dt>
                <dd class="card-row__definition">1 упаковка (100 г)</dd>

                <dt class="visually-hidden">Цена</dt>
                <dd class="card-row__definition card-row__definition--price">200 р.</dd>
              </dl>
```

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +        <button class="additional-card-button button">Заказать</button>
Что-то со вложенностью не ок )

2022-12-03 21:23 UTC, wrgraff commented on source/form.html
> +            <li class="site-list__item site-list__item--current">
Это не активная страница )

2022-12-03 21:23 UTC, wrgraff commented on source/catalog.html
> +        <a class="logo">
Почему нет ссылки на главную с лого?
Посмотри вообще логику ссылок друг на друга. Делаем/не делаем ли ссылку на себя сперва реши, затем пересмотри ссылки в меню и с логотипов как в хэдере, так и в футере

2022-12-03 21:23 UTC, wrgraff commented on source/form.html
> +    <main class="form-container">
Хочется унифицированный мейн!

2022-12-03 21:23 UTC, wrgraff commented on source/form.html
> +      <form class="form-container__form order-form" action="#" method="post">
`action` можно сразу поставить академовский.
Не уверен, кстати, что хорошо подходит название блока `order-form`, потому что это не форма заказа )

2022-12-03 21:23 UTC, wrgraff commented on source/form.html
> +                <input class="radio__input" name="programm" type="radio" value="diet" checked>
Скорее так
```suggestion
                <input class="radio__input" name="program" type="radio" value="diet" checked>
```

2022-12-03 21:23 UTC, wrgraff commented on source/form.html
> +            </label>
Очень не рекомендую ставить контент внутри тега в строку с открывающей частью, если внутри уже на отдельных строках все размещено:
```suggestion
            <label class="form-group__field field">
              Телефон:*
              <input class="field__input" name="phone" type="tel" placeholder="8 (960) 900-60-90">
            </label>
```

Большая вероятность того, что такой текст в конце тега останется незамеченным

2022-12-03 21:23 UTC, wrgraff commented on source/form.html
> +            <label class="form-group__field field">e-mail:*
А куда делся `field__text`? Был же в инпутах повыше

2022-12-03 21:23 UTC, wrgraff commented on source/form.html
> +        </p>
У тебя получается, что `field__input` идет не внутри блока, а после него

2022-12-04 13:32 UTC, anastasia-sp commented on source/catalog.html
> +          <p class="gift-section__text">Закажите все и получите чехол для кота в подарок!</p>
странно, у меня в редакторе нормальный 🤔

2022-12-05 20:52 UTC, wrgraff commented on source/index.html
> +      </dl>
Не, не 2 списка парных значений )
А или обычный список из двух пунктов, внутри каждого написана пара.
Или — список парных значений, но список один )
```suggestion
      <dl class="example__table result">
        <dt class="result__title">снижение веса</dt>
        <dd class="result__value">5 кг</dd>

        <dt class="result__title">затрачено времени</dt>
        <dd class="result__value">60 дней</dd>
      </dl>
```

2022-12-05 20:52 UTC, wrgraff commented on source/index.html
> +        <dt class="result__title">затрачено времени</dt>
А почему с маленькой буквы то

2022-12-05 20:52 UTC, wrgraff commented on source/index.html
> +          <span class="visually-hidden">слайдер</span>
Странное описание: непонятно, что это именно "хваталка" слайдера. И почему с маленькой буквы?

2022-12-05 20:52 UTC, wrgraff commented on source/form.html
> +  <main class="main-container selection">
Ну в принципе появился общий блок, но и индивидуальный никуда не исчез

2022-12-05 20:52 UTC, wrgraff commented on source/catalog.html
> +        <h4 class="additional-card__title">Питьевая вода</h4>
Ну а тут то почему 4-й уровень

2022-12-05 20:52 UTC, wrgraff commented on source/catalog.html
> +    <section class="catalog__section additional-products">
Получается, этот секшн остался без собственного заголовка?

2022-12-05 20:52 UTC, wrgraff commented on source/catalog.html
> +          <p class="gift-section__text">Закажите все и получите чехол для кота в подарок!</p>
Что-то с ними вообще все странно, проверь установлен ли плагин editorconfig и все ли нормально там с ним работает.
Нет ли там табов местами.

2022-12-05 21:02 UTC, wrgraff requested changes

2022-12-05 21:02 UTC, wrgraff commented on source/form.html
> +      </p>
```suggestion
      <p class="selection-form__group form-group">
        <label class="form-group__title field">
          Комментарий
          <textarea class="field__input" name="text" rows="4" placeholder="Расскажите обо всех повадках кота"></textarea>
        </label>
      </p>
```

2022-12-05 21:02 UTC, wrgraff commented on source/catalog.html
> +            <h2 class="card__title-name">
Понятно, что по структуре подходит, но в целом довольно странно, что заголовок товара одного уровня с целой секцией контакты. И выглядит не очень логично, можно посмотреть в [HTML tree](https://yoksel.github.io/html-tree/) (там и ошибочки есть, но не в этом месте)

<img width="584" alt="изображение" src="https://user-images.githubusercontent.com/37917037/205742045-b718c9db-79f2-4030-9433-f804294cc228.png">

2022-12-06 16:33 UTC, anastasia-sp commented on source/catalog.html
> +          <p class="gift-section__text">Закажите все и получите чехол для кота в подарок!</p>
Всё установлено. Отформатировала все три файла на всякий.

2022-12-06 16:37 UTC, anastasia-sp commented on source/form.html
> +  <main class="main-container selection">
кажется, до меня дошло) но я не уверена

2022-12-06 18:29 UTC, wrgraff requested changes

2022-12-06 18:29 UTC, wrgraff commented on source/catalog.html
> +    <section class="main-container__section products">
Так симпатичнее )

2022-12-06 18:29 UTC, wrgraff commented on source/catalog.html
> +      <h2 class="products__title">
Я бы наверное этот заголовок сделал h1, а в секцию добавил невидимый h2 с текстом вроде "список товаров".

2022-12-06 18:29 UTC, wrgraff commented on source/catalog.html
> +  <h1 class="visually-hidden">Каталог продукции магазина «Кэт Энерджи»</h1>
Наверное, перед хэдером все-таки перебор, может в мейн его переместить?
Обычно то они у нас в нем...

2022-12-06 18:29 UTC, wrgraff commented on source/form.html
> +  <h1 class="visually-hidden">Форма записи на подбор программы питания</h1>
Но ведь у нас есть хороший заголовок первого уровня...

https://github.com/htmlacademy-adaptive/1902231-cat-energy-27/blob/3dd8c8e1ed3dedf614488bfef8e11033543e667e/source/form.html#L35

А 2 заголовка это ошибка, первоуровневый только один должен быть.

2022-12-06 18:29 UTC, wrgraff commented on source/index.html
> +  <h1 class="visually-hidden">Интернет-магазин кошачьего корма «Кэт Энерджи»</h1>
И тут есть уже, и на удивление хорошо подходит...
https://github.com/htmlacademy-adaptive/1902231-cat-energy-27/blob/3dd8c8e1ed3dedf614488bfef8e11033543e667e/source/index.html#L35

2022-12-06 19:13 UTC, wrgraff approved these changes

2022-12-06 19:13 UTC, merged