Добавляет стилизацию
htmlacademy-adaptive/1902231-cat-energy-27 pull request #3
Opened 2022-12-12 20:09 UTC by anastasia-sp

2022-12-15 11:53 UTC, wrgraff requested changes
Вышло очень даже хорошо!
Подокапывался до некоторых деталей и нашел несколько упущений )

2022-12-15 11:53 UTC, wrgraff commented on package.json
> +    "start": "npx gulp"
Хм, а должно и так работать вообще. Не работает?

2022-12-15 11:53 UTC, wrgraff commented on source/catalog.html
> +      <img class="logo__image" src="./img/footer-logo.png" width="128" height="24" alt="Cat Energy">
А почему у них разный стиль описания пути?
Нужно делать единообразно, при чем по всему проекту. Я так понимаю, у тебя через точку все раньше написано было:

```suggestion
      <img class="logo__image" src="./img/logo-mobile.png" width="33" height="37" alt="Магазин «Кэт Энерджи»">
      <img class="logo__image" src="./img/footer-logo.png" width="128" height="24" alt="Cat Energy">
```

Ну или без точки, тут выбирай как нравится — главное, чтобы единообразно было.
И посмотри по всему проекту как сделано, а то я вижу, что немного разнится это.

2022-12-15 11:53 UTC, wrgraff commented on source/catalog.html
> +  <link rel="stylesheet" href="css/style.css">
```suggestion
  <link rel="stylesheet" href="./css/style.css">
```

2022-12-15 11:53 UTC, wrgraff commented on source/catalog.html
> +      <img class="logo__image" src="./img/footer-logo.png" width="128" height="24" alt="Cat Energy">
Смотри, картинки у нас две и по логике обе контентные. Но в то же время они как бы составные части одного логотипа. Поэтому, чтобы не путать никого, можно одну оставить с нормальным описанием, а другую наоборот оставить с пустым и спрятать через `aria-hidden="true"`

2022-12-15 11:53 UTC, wrgraff commented on source/form.html
> +      <img class="contacts__map" src="img/map.png" width="320" height="362" alt="Карта.">
Кстати, `alt` с текстом "Карта" не очень хорош. Можно было бы для незрячих добавить описание, которое могло бы им помогать найти место.
Не знаю насколько это реально в нашем учебном проекте, но можно попробовать написать что-то вроде "от остановки прямо 2 перекрестка и направо". Ну или как там в офис Академии попасть, это ж адрес офиса ))

2022-12-15 11:53 UTC, wrgraff commented on source/index.html
> +        <img class="example__image" src="img/cat-before.png" width="280" height="232" alt="Кот до перехода на питание Cat Energy">
Картинки нужны для работы слайдера не половинчатые, а целые )

2022-12-15 11:53 UTC, wrgraff commented on source/catalog.html
> +            <img class="card__logo-image" width="72" height="84" src="img/catalog/slim500(rice).png" alt="Корм «Cat Energy SLIM» со вкусом риса в упаковке 500 грамм.">
Скобки в названиях файлов недопустимы, только буквы, цифры и дефис (файл с лого Академии тоже надо поменять, там нижнее подчеркивание)

2022-12-15 11:53 UTC, wrgraff commented on source/catalog.html
> +      <img class="logo__image" src="./img/footer-logo.png" width="128" height="24" alt="Cat Energy">
Логотип в футере на самом деле такой же, как и в хэдере. Это как раз одна из двух картинок, где только текстовая часть.
Они могут немного отличаться по размеру, но это svg и его можно спокойно масштабировать.

2022-12-15 11:53 UTC, wrgraff commented on source/index.html
> +      <img class="logo__image" src="./img/footer-logo.png" width="128" height="24" alt="Cat Energy">
Почему-то все логотипы растровые, хотя это векторные картинки:
<img width="509" alt="изображение" src="https://user-images.githubusercontent.com/37917037/207841037-70e39bd4-02ea-4ec2-9903-509118712360.png">

2022-12-15 11:53 UTC, wrgraff commented on source/index.html
> +        <dd class="result__title">Снижение веса</dd>
Так у тебя получается, что "5 кг" — это название параметра, а "Снижение веса" — его значение.
Должно быть наоборот.

(ага, в разметке они будут идти в обратном от макета порядке, но нас это не должно пугать)

2022-12-15 11:53 UTC, wrgraff commented on source/sass/variables.scss
> +$font-text: "Loto", sans-serif;
К сожалению, у нас до сих пор в [требованиях](https://up.htmlacademy.ru/adaptive/27/criteries#b10) веб-безопасные шрифты стоят (по мне так это почти бесполезно и нужно в очень редких случаях, но критерий есть критерий)

2022-12-15 11:53 UTC, wrgraff commented on source/sass/fonts.scss
> +        url("../fonts/lato/Lato-Regular.woff") format("woff");
Только файл все-таки должен быть назван исключительно в нижнем регистре
```suggestion
    src: url("../fonts/lato/lato-regular.woff2") format("woff2"),
        url("../fonts/lato/lato-regular.woff") format("woff");
```

В названиях файлов и папок нам нужно придерживаться нижнего регистра. Дело в том, что некоторые операционные системы учитывают регистр, а некоторые нет.

Может случиться так, что работал ты в системе, что регистр не учитывает, а проект опубликован в той, что учитывает. И тогда у тебя все будет работать, несмотря на разные буквы, а в опубликованной версии — нет. И это будет совсем не здорово.

Поэтому разработчики условились всегда называть файлы и папки в нижнем регистре (на самом деле нет, но пока ограничимся этим).

> Может случиться так, что изменения регистра не попадают в коммит, как раз из-за того, что система разницы между этими названиями не видит.
Верный способ решить это по простому: кроме смены регистра переименовать файл как-то более заметно (добавить цифру 0, например), закоммитить и затем удалить ненужный символ и еще раз закоммитить. Так изменения точно попадут в коммит.

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/additional_products.scss
> +    line-height: 24px;
Насколько помню, у Академии в стайлгайде отступ в 2 пробела, а не 4.
У тебя точно есть какая-то проблема с форматированием файлов: или они не работают или наоборот ты подключила какой-то форматтер, который все ломает

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/main.scss
> +    margin: 0 20px;
БЭМ-блокам нельзя задавать размеры и внешние отступы.
Основная идея блока в том, что он переиспользуемый, а значит должен подстраиваться под контент в зависимости от контекста.

Например, у нас есть БЭМ-блок `.card` в виде карточки товара. И есть страница с карточками товаров, где в сетке товаров каждая карточка занимает в ширину 320 пикселей.
Мы задаем БЭМ-блоку `.card` ширину 320 пикселей: а что такого?

![https://user-images.githubusercontent.com/37917037/127750217-6f72b53c-d8ce-402b-b342-0cbe69453432.png](https://user-images.githubusercontent.com/37917037/127750217-6f72b53c-d8ce-402b-b342-0cbe69453432.png)

Но на другой странице мы встречаем боковой список товаров, где конечно же будет логично использовать наш блок `.card` снова. Ставим его туда, и наша сетка "едет": оказывается, там меньше места, и нам нужна карточка 280 пикселей шириной. Но из-за заданного размера карточка "торчит" из контейнера.

![https://user-images.githubusercontent.com/37917037/127750221-7c75880d-5832-4b36-acc4-a071c24fc080.png](https://user-images.githubusercontent.com/37917037/127750221-7c75880d-5832-4b36-acc4-a071c24fc080.png)

Поэтому у блока размеров быть не должно: БЭМ-блок `.card` должен подстроиться под ширину кониейнера или колонки, в котором он находится: эти размеры определяются тем контекстом, в котором мы его используем.

Аналогичная ситуация и с отступами (но пример с размером более нагляден). Отступы так же должны быть определены контекстом, в котором использован БЭМ-блок: через элементы или gap'ы в сетке. Блок не должен ничего сдвинуть или сместить в своем окружении.

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/main.scss
> +    margin: 0 20px;
Важный момент: в Академии на это внимание обращать не принято и смотрят только на нейминг.
Мы тоже можем ограничиться неймингом на данном этапе. Просто дай мне знать, будем ли мы более строго следовать БЭМу или пока что нет, чтобы я знал, обращать ли внимание на такие нюансы в будущем

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/site-list.scss
> +    margin: 0;
Есть проблема не только с установкой, но и с обнулением отступов у БЭМ-блоков. Хотя, казалось бы обнуление — это же не установка отступа, а удаление?..

Но суть проблемы в том, что обнуление внутри блока точно так же может случайно переписать свойства элемента, как и указание какого-то конкретного размера.
Потому что технически мы не обнуляем, а назначаем отступ, равный нулю. Поэтому даже обнуления придется делать через элементы.

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/show-more-section.scss
> +    font-weight: 400;
Очень много мест, где у тебя стоит `font-weight: 400;`
Но так же, как и `font-family` это наследуемое свойство, а 400 — это значение по умолчанию.
Получается, что это лишний код. Кроме тех случаев, когда у тега меняется вес шрифта в браузерных стилях (например, `<h1>` – `<h6>`, `<strong>`, `<b>`) или когда мы переназначаем свои стили, которые отнаследовались.

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/show-more-section.scss
> +    color: $color-gray-600;
Цвета кнопкам лучше менять через модификаторы блока кнопки.
Потому что изначально они заданы там, а в этом блоке это элемент, который скорее за расположение кнопки отвечает

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/preview.scss
> +    background-image: url(../../img/index-background.png);
Неправильный путь к файлу. Препроцессор не умеет при сборке переписывать пути к картинкам. Это обычная статическая строка. Поэтому нам нужно писать путь исходя из того, где находится наш скомпилированный css-файл.

У нас директория `img` находится обычно рядом с директорией `css`, а значит нужно один раз выйти из директории(`../`) и зайти в картинки.

> Почему же при всем при этом картинки работают?
Потому, что лишние выходы на уровень выше не срабатывают, так как мы сразу попадаем в корневую директорию. Однако, если мы сделаем тоже самое на сервере с другими настройками, то будет проблема. Например, попробуй опубликовать свой пул-реквест в интерфейсе проверки задания (прямо в интерфейсе Академии есть такая кнопка)
>

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/main.scss
> +.main-header {
Это файл БЭМ-блока `main`. В нем не может быть `main-header`, `main-container` и `main-footer`, это другие блоки.
Один блок — один файл.

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/gift-section.scss
> +    background-image: url("../../img/catalog/gift-section.png");
Так как ошибка с путями повторяется, не забудь проверить их все!

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/gift-section.scss
> +    min-height: 280px;
Это возможно иногда (на самом деле очень редко) нужно использовать при построении сеток.
Сейчас рано.

Мне не очень нравится, когда рекомендуют минимальной высотой создать элементу вид как на макете, потому что это позволяет забыть про переполнение.
Минимальная высота — [способ работы с недополнением контентом](https://mentorium.frontend-design.ru/articles/height-in-css/). И только с ним.

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/form-options.scss
> +
2 пустые строки.
Обрати внимание вообще, проходит ли проект проверку линтером (спойлер: нет)

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/field.scss
> +    box-sizing: border-box;
Применять изменение способа подсчета размера по месту — какая-то безумная идея, которая никогда не попадается в реальности.
Я писал почему лучше действовать [иначе](https://frontend-design.notion.site/box-sizing-2f4e2359a3f14470bd89e1379f4e4f8f)

2022-12-15 11:53 UTC, wrgraff commented on source/sass/blocks/button.scss
> +  padding: 7px 44px;
Очень большие паддинги, кажется.
Лучше в самой кнопке оставить такой отступ, чтобы текст не прилипал к краям и хорошо смотрелся.

А размер кнопки (если он не по тексту) пускай формируется элементом вышестоящего блока. С которым он смиксован.

2022-12-16 14:08 UTC, anastasia-sp commented on package.json
> +    "start": "npx gulp"
У нас в [статье](https://up.htmlacademy.ru/adaptive/27/module/3/item/12) написано, что если пользуетесь git bash `gulp` не запустится, и нужно запустить `gulp` с помощью `npx`

2022-12-16 20:01 UTC, anastasia-sp commented on source/form.html
> +      <img class="contacts__map" src="img/map.png" width="320" height="362" alt="Карта.">
больше мы по нему не живём :) но альт с дорогой прописала

2022-12-16 20:20 UTC, anastasia-sp commented on source/form.html
> +      <img class="contacts__map" src="img/map.png" width="320" height="362" alt="Карта.">
Мы там больше не живём :) но альт с дорогой прописала.

2022-12-16 20:47 UTC, anastasia-sp commented on source/sass/blocks/main.scss
> +    margin: 0 20px;
Давай более строго следовать, я за. В таком случае пока убираю отступы и добавлю уже точечно вместе с сетками, получается

2022-12-16 21:01 UTC, anastasia-sp commented on source/sass/blocks/preview.scss
> +    background-image: url(../../img/index-background.png);
Но у меня же этот файл находится внутри папки `blocks`. Разве если я лишь один раз выйду из директории, я не окажусь в этой папке `blocks`?

2022-12-17 15:25 UTC, wrgraff commented on package.json
> +    "start": "npx gulp"
Интересно. Я им мало пользовался и не помню такого.
А у тебя прям не запускалось, да?

2022-12-17 15:28 UTC, wrgraff commented
Обрати внимание, что не проходит проверку проект:
<img width="910" alt="изображение" src="https://user-images.githubusercontent.com/37917037/208249175-6cbd953e-2071-4e8d-bcb2-fc537d9fa4bf.png">

То есть, я заранее еще не начав, вижу, что принимать нельзя такую домашку =)
Ты можешь локально запускать `npm run lint` и посмотреть в чем проблема. Если что-то будет непонятное там в терминале или не получится исправить, то пиши мне — будем разбираться

2022-12-17 15:38 UTC, wrgraff commented on source/index.html
> +      <img class="logo__image" src="./img/footer-logo.svg" width="128" height="24" aria-hidden="true">
Ой, `alt=""` то надо было оставить, но пустым. Без него ты валидацию не пройдешь

2022-12-17 15:38 UTC, wrgraff commented on source/form.html
> +      <img class="contacts__map" src="img/map.png" width="320" height="362" alt="Карта.">
Шикарное описание, его бы текстом не мешало добавить, а то я когда-то с трудом вас нашел =)

2022-12-17 15:49 UTC, wrgraff commented on source/sass/blocks/main.scss
> +    margin: 0 20px;
Договорились, но если будет много времени занимать, то дай знать =)

2022-12-17 15:52 UTC, wrgraff commented on source/sass/blocks/site-list.scss
> -    padding: 0;
Паддинг — внутренний отступ, то есть он не действует за пределами БЭМ-блока. Его можно спокойно использовать

2022-12-17 15:52 UTC, wrgraff commented on source/sass/blocks/preview.scss
> +    background-image: url(../../img/index-background.png);
Это у тебя в исходнике есть папка `blocks`, а сам браузер подключает один-единственный css-файл, который лежит в папке `css`. И вот именно от этого файла будет работать путь

2022-12-17 15:55 UTC, wrgraff requested changes

2022-12-17 15:55 UTC, wrgraff commented on source/sass/blocks/form-options.scss
> -
Так должна быть пустая строка же )
Но одна! Не две )

2022-12-17 15:55 UTC, wrgraff commented on source/sass/blocks/field.scss
> -    box-sizing: border-box;
А глобально не будем включать?
Удобнее же так размеры считать =)

2022-12-17 17:54 UTC, anastasia-sp commented on package.json
> +    "start": "npx gulp"
Я, если честно, и не проверяла, просто сразу сделала, как было написано в статье 🤔 Нужно убрать?

2022-12-17 17:56 UTC, anastasia-sp commented on source/form.html
> +      <img class="contacts__map" src="img/map.png" width="320" height="362" alt="Карта.">
Теперь всё проще, пять-семь минут от Петроградской и вы на месте)

2022-12-17 18:02 UTC, anastasia-sp commented on source/sass/blocks/form-options.scss
> -
Там одна осталась, да.

2022-12-19 14:01 UTC, wrgraff commented on source/sass/style.scss
> +@import "global.scss";
А почему без точки, путь то в одном стиле стоит писать )
```suggestion
@import "./global.scss";
```

2022-12-19 14:01 UTC, wrgraff commented on package.json
> +    "start": "npx gulp"
Да не прям нужно, мне интересно было ))
Но обычно если "и так работает", то лучше и не трогать =)

2022-12-19 14:01 UTC, wrgraff approved these changes

2022-12-19 14:01 UTC, merged