Добавляет сетки
htmlacademy-adaptive/1902231-cat-energy-27 pull request #4
Opened 2022-12-19 19:27 UTC by anastasia-sp

2022-12-22 17:42 UTC, wrgraff requested changes

2022-12-22 17:42 UTC, wrgraff commented on source/index.html
> +  <div class="page__container">
Ну нееееет, все сломалось так )
Общий контейнер тут не только нет необходимости создавать (можно же было бы отцентрировать сам `page__body` или отдельно 3 блока хэдера, мейна и футера.

Но дело то даже в том, что эта штука скорее ломает нам сетку. Если все заключить в общий контейнер фиксированной ширины — как мы сможем задать отдельным секциям фон от края до края?

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/catalog-section.scss
> +  gap: 20px;
На данный момент для работы с сетками существует 3 контекста: flex, grid… и обычная блочная модель, существующая по умолчанию. Раньше для сеток использовали и другие хаки, но мы про них успешно позабыли, как о страшном сне.

Но часто я вижу, что код пишется так, будто вариантов всего 2: флекс или грид. И флекс почему-то еще и служит вариантом, который надо включать по умолчанию.

Если нам нужно добиться того, чтобы элементы просто стояли в одной колонке друг под другом, растягиваясь на всю ширину — что мы можем сделать? Например, можем попробовать флекс:

![изображение](https://user-images.githubusercontent.com/37917037/209180452-474cf08a-ca0b-4ac5-9c4e-381831296756.png)

Получилось! Так, подожди-ка… А что у нас на первом варианте до внедрения флекса? Так у нас и так был искомый результат. А зачем мы написали аж целых 2 свойства, чтобы его добиться?
Кстати, с гридом картинка будет еще смешнее:

![изображение](https://user-images.githubusercontent.com/37917037/209180408-02e666ba-c888-4bdb-bbba-9e730277930f.png)

Вообще никакой разницы =)

Итого, чтобы добиться искомого поведения элементов мы можем сделать несколько вещей. Распределим их по количеству действий:

- применить флекс и сменить направление (2 действия);
- применить грид (1 действие);
- ничего (0 действий).

Если можно ничего не делать — зачем что-то делать?

Другой вопрос, если понадобились какие-то специфические свойства этих технологий. Например, если у нас равные отступы (если не равные, то смысла нет), мы хотим использовать gap. Но и тут есть подвох: у грида поддержка гэпов лучше, чем у флекса. И гриду не надо менять направление, он сразу построчно создаст элементы.

Возможно, мы хотим какой-то элемент всегда прижимать вниз блока. Или центрировать, менять порядок — что-то из этого. И опять же, каждый раз выбор между гридом и флексом будет не настолько очевиден.

Поэтому я попрошу каждое вот такое включение колонки прокомментировать: есть ли тут реальная причина. Потому что повсеместно, просто по умолчанию любую последовательность элементов превращать в колоночный флекс — не очень правильно.

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/catalog-section.scss
> +  flex-direction: column;
А вот тут колоночный флекс нам зачем?

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/catalog-section.scss
> +@media (min-width: $tablet-width) {
А тебе так удобно? Мне удобнее писать наоборот: класс, а в нем сперва один меди-запрос, потов второй. И стили для одного элемента получается лежат вместе.

```scss
.some-element {
  ...

  @media (min-width: $tablet-width) {
    ...
  }

  @media (min-width: $desktop-width) {
    ...
  }
}
```

Так можно благодаря препроцессору. Он вложенные медиа-запросы потом разворачивает.
Просто имей ввиду, что так тоже можно

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/catalog-section.scss
> +    justify-content: space-between;
А как проще создать 2 равные колонки (сейчас кстати равные не получились): флексом или гридом?

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +  flex-wrap: wrap;
Нуууу, допустим флекс, а `wrap` тут с какой целью?

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    column-gap: 300px;
Медиа-запрос работает же от указанного размера и выше. То есть, у нас и на десктопе будет такой же гэп. А для него это ту мач.

Я кстати не очень понял, зачем он у тебя меняется, потому что если ты уже раскидала по разным краям элементы через `justify-content: space-between;`, то зачем еще и гэп?

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/example.scss
> +  grid-template-columns: 280px;
А у тебя фикс или резина будет?
Если фикс, то так можно даже центрирование сделать гридом (но не факт, что надо).
А если не фикс (или мы так центрирование не делаем), то можно ничего и не писать: и так будет одна колонка, вписанная в доступную ширину.

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/example.scss
> +  }
Выглядит сложна

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/example.scss
> +    grid-template-columns: 185px 185px 320px;
В принципе, у тебя все элементы вписаны или в 3 колонки сразу, или в последнюю или в первые две.
То есть, в принципе достаточно 2 колонки.

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/example.scss
> +    grid-template-columns: 560px 560px;
Лучше конечно не в абсолютных единицах.
```suggestion
    grid-template-columns: 1fr 1fr;
```

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/example.scss
> +    grid-row: 1/-1;
Так как высота у нас определяется по мере наполнения, отсчет с обратной стороны не срабатывает (посмотри, там коты в первом ряду только).
Придется использовать или указание от верха или прием со `span` (это когда указываешь сколько рядов или колонок занять должен элемент).

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/how-work.scss
> +  flex-direction: column;
А тут точно нужен флекс колоночный?

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/how-work.scss
> +  flex-wrap: wrap;
Оооооо, а вот щас вопрос на засыпку!
Итак. Учитывая, что врап работает по основной оси — как он будет работать по вертикали? В каком случае он сработает и куда "врапнет" элемент?

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/how-work.scss
> +  width: 200px;
А почему не 280?
Зачем вообще ширина там )

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/how-work.scss
> +  }
У нас кстати не первый уровень, а на втором раньше даже считалось, что начинать крупные сетки строить надо с гридов...

Флекс хорош для таких вот штук:
![изображение](https://user-images.githubusercontent.com/37917037/209191581-64ebd4cb-2df8-44e7-8678-6bfe9a5eda6d.png)

А когда у нас ровные одинаковые колонки — хорош грид.
А еще мыслить не пикселями, а соотношениями очень потом поможет перейти на резину.
Там гэпи фиксированные, а колонки нет

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/main-header.scss
> +  flex-direction: column;
А здесь флекс что дает?

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/main-footer.scss
> +  flex-direction: column;
А здесь флекс что дает? =)

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  flex-direction: column;
А здесь флекс зачем?
Кстати, подвох в том, что где-то его использование может быть оправдано.
Или нигде не оправдано.
Не скажу. Надо реально не просто убрать его везде, где я понаписал вопрос зачем он нужен, а про каждый случай подумать: действительно, а зачем?

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/page.scss
> +  width: 320px;
Ну, что все сломалось я в разметке написал.
Тут хочу обратить внимание, что нет центрирования.

Иногда люди упускают это из-за того, что смотрят строго на разрешении как в макете.
Стоит всегда чуть увеличивать ширину и смотреть что произойдет на экране чуть более широкого устройства?

<img width="560" alt="изображение" src="https://user-images.githubusercontent.com/37917037/209192654-51b4e34f-74d7-4840-bd28-96777321c78f.png">

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/social.scss
> +  height: 20px;
Обычно иконки квадратные с центрированной картинкой внутри, а размер задают все-таки ссылке, ведь это в нее нам нужно нажать. И ее размер определяющий

2022-12-22 17:42 UTC, wrgraff commented on source/sass/variables.scss
> +$mobile-width-only: 767px;
Вот я не люблю этот паттерн по 2 причинам:
1. Это не ширина, а размер экрана, после которого срабатывает переход на следующую версию. Для этого есть термин брейкпоинт (breakpoint).
2. И мне не нравится (тут чуть больше вкусовщины), что у нас размеры называются "телефон", "планшет" и "десктоп". Нет никаких гарантий, что это будут именно они, тем более что грань между размерами этих устройств стирается (айфоны макс про все ближе к планшетам серии мини, а планшеты про все ближе к небольшим ноутбукам). Поэтому я предпочитаю более тупые имена: small / medium / large.

2022-12-22 17:42 UTC, wrgraff commented on source/sass/blocks/page.scss
> +}
`$desktop-width` — это 1220px.
Получается, как только мы достигаем ширины 1220, ты задаешь ширину 1440. А как оно туда поместится? =)

2022-12-26 14:23 UTC, anastasia-sp commented on source/sass/blocks/catalog-section.scss
> +  gap: 20px;
Спасибо за такой подробный комментарий! 

Да, про блочную модель я забыла. Здесь использовала флекс, чтобы при переходе на десктоп просто поменять главную ось. Почему-то я подумала, что лучше применить флекс в телефонной версии, а дальше уже только менять направление при необходимости (и этой логикой пользовалась во всех следующих случаях). 

Но если посчитать по количеству действий, получается, что я для телефона задаю колоночный флекс в два действия, а потом меняю его на рядный (или рядовой?) ещё одним действием в десктопе. Тогда как можно оставить для телефона блочную модель и просто задать флекс по месту, где это необходимо (и в одно действие). А ещё лучше, наверное, будет применить грид на две колонки, тогда я смогу задать им ширину и они будут одинаковые (а то сейчас они что-то не очень одинаковые). 

Здесь аргументов, которые могут это побить, у меня не нашлось. Меняю на грид и иду думать про другие колоночные флексы)

2022-12-26 14:43 UTC, anastasia-sp commented on source/sass/blocks/catalog-section.scss
> +  flex-direction: column;
По той же логике, что и в случае выше. Но ещё и чтобы задать отступ между элементами. Забыла, что внешние отступы нельзя задавать только блокам, видимо решила не использовать их теперь вовсе)

2022-12-26 14:44 UTC, anastasia-sp commented on source/sass/blocks/catalog-section.scss
> +@media (min-width: $tablet-width) {
Не знала про такой способ. Так и вправду удобнее.

2022-12-27 08:43 UTC, wrgraff commented on source/sass/blocks/catalog-section.scss
> +  gap: 20px;
Зря забыла, она же существует по умолчанию )

2022-12-27 08:44 UTC, wrgraff commented on source/sass/blocks/catalog-section.scss
> +@media (min-width: $tablet-width) {
Да, главное в CSS так не писать, это именно возможность препроцессора (по крайней мере пока что)

2023-01-04 11:40 UTC, anastasia-sp commented on source/sass/blocks/contacts.scss
> +  flex-wrap: wrap;
Чтобы карта перенеслась на следующий ряд. Так нельзя?)

2023-01-04 11:42 UTC, anastasia-sp commented on source/sass/blocks/contacts.scss
> +    column-gap: 300px;
Я задала ширину элементам. space-between задала, чтобы раскидать их по краям, а колумн-гэп, чтобы карта не помещалась и переносилась на следующий ряд флекса. Есть смутное сомнение, что это не логично и не правильно, судя по реакции ракеты, но я что-то не соображу, как тут сделать иначе.

2023-01-04 11:42 UTC, anastasia-sp commented on source/sass/blocks/example.scss
> +  grid-template-columns: 280px;
Фикс, я думаю.

2023-01-04 11:48 UTC, anastasia-sp commented on source/sass/blocks/example.scss
> +  }
так не надо?

2023-01-04 11:58 UTC, anastasia-sp commented on source/sass/blocks/how-work.scss
> +  flex-direction: column;
Наверное, нет. Всё это я затеяла ради гэпа, но отступ можно задать через марджины, а в планшетной и десктопной версии, наверное и вовсе сделать этот блок гридом, так как колонки и там, и там колонки

2023-01-04 12:05 UTC, anastasia-sp commented on source/sass/blocks/how-work.scss
> +  flex-wrap: wrap;
я уже убрала оттуда флексы, но так как вопрос на засыпку, предположу, что он сработает при переполнении (а для этого, получается, нужно задать высоту, чего мы стараемся не делать), а сам элемент врапнет в новую колонку справа

2023-01-04 12:07 UTC, anastasia-sp commented on source/sass/blocks/how-work.scss
> +  width: 200px;
я хотела ограничить текст, чтобы осталось место для иконки, но не подумала, что я так всему айтему задаю ширину. Убрала

2023-01-04 12:07 UTC, anastasia-sp commented on source/sass/blocks/how-work.scss
> +  }
исправила на грид

2023-01-04 12:14 UTC, anastasia-sp commented on source/sass/blocks/main-header.scss
> +  flex-direction: column;
Получается, особо ничего. С блоком будет также, а вот в планшетной уже можно задать просто флекс, и там будет всё перестраиваться, как нужно.

2023-01-04 12:16 UTC, anastasia-sp commented on source/sass/blocks/main-footer.scss
> +  flex-direction: column;
тоже ради гэпа, не стоит?

2023-01-04 12:22 UTC, anastasia-sp commented on source/sass/blocks/main-nav.scss
> +  flex-direction: column;
Да, я каждый случай обдумывала и через инспектор смотрела, что даёт) это сложно вспоминать через время, но полезно. 

Здесь убрала, потому что флекса на самом хедере при переходе на планшет и десктоп дотаточно, получается

2023-01-04 12:27 UTC, anastasia-sp commented on source/sass/variables.scss
> +$mobile-width-only: 767px;
Про брейкпоинт не очень поняла. Нужно изменить название переменной? 

По поводу названий, могу я пока оставить так, а перед защитой заменить?

2023-01-04 21:02 UTC, wrgraff commented on source/sass/blocks/catalog-section.scss
> +  flex-direction: column;
Ну использование гэпа — вполне себе аргумент. Иногда может быть с ним настолько удобнее, что оно того стоит

2023-01-04 21:05 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +  flex-wrap: wrap;
Я боюсь, что так не получится реализовать решение, в котором текст поверх карты на десктопе (я кстати про него видео присылал же)

2023-01-04 21:11 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    column-gap: 300px;
Можно сделать примерно так, как тут: https://youtu.be/Ccmu3wrjY8o
=)

2023-01-04 21:12 UTC, wrgraff commented on source/sass/blocks/example.scss
> +  grid-template-columns: 280px;
Принято к сведению )

2023-01-04 21:14 UTC, wrgraff commented on source/sass/blocks/example.scss
> +  }
Можно, я просто все время, когда такие перестроения делаю, то очень сложно понять потом что происходит.
Обычно в итоге переписываю с `grid-template-areas`. Там как-то наглядно получается, попробуй если хочешь )

2023-01-04 21:18 UTC, wrgraff commented on source/sass/blocks/how-work.scss
> +  flex-direction: column;
Можно чтобы отступы не переписывать потом, сразу применить грид и воспользоваться гэпом.

2023-01-04 21:19 UTC, wrgraff commented on source/sass/blocks/how-work.scss
> +  flex-wrap: wrap;
Точно!
Ты мозг =)

2023-01-04 21:26 UTC, wrgraff commented on source/sass/blocks/main-footer.scss
> +  flex-direction: column;
Можно, но у футера там есть особенность, из-за которой флекс может быть проблемным. Обрати внимание, что элементы стоят слева, по центру и справа, но расстояние между элементами не равное:
![изображение](https://user-images.githubusercontent.com/37917037/210652923-9acff117-02a9-48a5-b10c-54a34d3cebcd.png)

2023-01-04 21:38 UTC, wrgraff commented on source/sass/blocks/page.scss
> +    .page__body {
А зачем он вложен в `.page`?

2023-01-04 21:38 UTC, wrgraff commented on source/sass/blocks/page.scss
> +    }
Ну нет, я же написал в смысле, что мы могли бы отцентрировать сам `<body>`, но на самом деле не можем.

Нам ведь нужно добиться того, чтобы фоны тянулись, а контент оставался по центру:

![изображение](https://user-images.githubusercontent.com/37917037/210654441-107a78f8-4080-44e3-9445-d80f68991e15.png)

2023-01-04 21:38 UTC, wrgraff commented on source/sass/variables.scss
> +$mobile-width-only: 767px;
Ну в моем понимании `$breakpoint-large` отражает суть гораздо лучше =)
Ты можешь менять сразу, потом или не менять — дело твое, это же не критичный момент.

2023-01-04 21:39 UTC, wrgraff requested changes
Главное все-таки с центрированием теперь разобраться и растяжимыми фонами

2023-01-08 22:33 UTC, wrgraff requested changes

2023-01-08 22:33 UTC, wrgraff commented on source/sass/variables.scss
> +$breakpoint-large: 767px;
Ээээ, не, это совсем не то ))

`$breakpoint-large` должен был быть вместо `$desktop-width`.
А в этом как-то не очень смысл прослеживается )

2023-01-08 22:33 UTC, wrgraff commented on source/catalog.html
> +        <div class="additional-products__cards">
А зачем везде по 2 обертки?
Одна — понятно, а вторая?
Или одна центрирует, а другая сетку создает? Но можно же и сетку прописать и центрирование одному и тому же wrapper'у

2023-01-08 22:33 UTC, wrgraff commented on source/catalog.html
>        <h2 class="additional-products__title">Дополнительные товары</h2>
А заголовок то разве не должен вписываться в контент?

2023-01-08 22:33 UTC, wrgraff commented on source/sass/blocks/additional-card.scss
> +  grid-template-columns: 280px;
Зачем же так сложно?
Можно же ограничить ширину еще для `additional-products__wrapper`.
Он же для этого и есть

2023-01-08 22:33 UTC, wrgraff commented on source/sass/blocks/additional-card.scss
> +  justify-content: space-between;
А зачем им спейс-битвин, если они в сумме всю ширину заняли и стоят вплотную?
Он же ничего не делает получается

2023-01-08 22:33 UTC, wrgraff commented on source/sass/blocks/additional-card.scss
> +    border: 1px solid $color-gray-300;
Это декор же.
К тому же, у тебя так задваиваются полоски между карточками. Лучше сделать у всего списка доп товаров рамку, а между ними — полоски.

2023-01-08 22:33 UTC, wrgraff commented on source/sass/blocks/additional_products.scss
> +    align-items: center;
Там вроде этот зеленый квадрат растягиваться должен на высоту доп товаров, а не вставать по центру

2023-01-08 22:33 UTC, wrgraff commented on source/sass/blocks/additional_products.scss
> +    justify-items: center;
А зачем элементам грида выравниваться в центре собственных колонок (это свойство именно это делает)?

2023-01-08 22:33 UTC, wrgraff commented on source/sass/blocks/gift-section.scss
> +  background-image: linear-gradient($color-gradient, $color-gradient), url("../img/catalog/gift-section.png");
Вам это подсказывают где-то?
Все никак не пойму, чего бы картинку не экспортировать сразу зеленой...

2023-01-10 09:34 UTC, anastasia-sp commented on source/sass/blocks/gift-section.scss
> +  background-image: linear-gradient($color-gradient, $color-gradient), url("../img/catalog/gift-section.png");
А так можно што ли? Вот это да, вот это открытие)) 

Про подсказку — на ретро в 5 разделе, кажется, Андрей смотрел что-то в коте и обратил внимание, как у студента сделан этот блок. Там был использован градиент.

2023-01-11 21:30 UTC, anastasia-sp commented on source/sass/blocks/additional-card.scss
> +    border: 1px solid $color-gray-300;
пока уберу тогда, там же они ещё тянуться должны

2023-01-11 21:32 UTC, anastasia-sp commented on source/sass/blocks/additional_products.scss
> +    align-items: center;
хм, а как это сделать?

2023-01-12 16:17 UTC, wrgraff commented on source/sass/blocks/gift-section.scss
> +  background-image: linear-gradient($color-gradient, $color-gradient), url("../img/catalog/gift-section.png");
Все время делают градиентом, но чтобы реализовать все полностью, понадобится 3 фона:
- градиент для тянущейся наполовину зеленой штуки
- градиент для перекрытия картинки
- картинка

Можно, но запарно )

2023-01-12 16:18 UTC, wrgraff commented on source/sass/blocks/additional_products.scss
> +    align-items: center;
А вроде бы по умолчанию работает выравнивание stretch, которое как раз растягивает )

2023-01-12 16:19 UTC, wrgraff commented on source/sass/blocks/additional-card.scss
> +    border: 1px solid $color-gray-300;
Не, тут вроде не должны: на мобильнике они на расстоянии, а дальше есть общая рамка

2023-01-12 16:26 UTC, wrgraff reviewed
Переходи скорее же к странице формы!
А еще футер не центрируется и блок контактов. Тоже посмотри.

2023-01-12 16:26 UTC, wrgraff commented on source/index.html
> +      <div class="preview-wrapper">
```suggestion
      <div class="preview__wrapper">
```

2023-01-12 16:26 UTC, wrgraff commented on source/sass/blocks/products.scss
> +    grid-template-areas: "title title";
Кажется, тут все-таки было проще написать для заголовка `grid-column: 1 / -1`, при чем это работать будет как надо сразу на все разрешения, так как такому правилу не важно сколько колонок: заголовок всегда займет всю строку целиком

2023-01-16 23:03 UTC, wrgraff requested changes
Чуток поправок и будем двигать дальше

2023-01-16 23:03 UTC, wrgraff commented on source/sass/blocks/field.scss
> +  grid-template-columns: min-content auto;
`min-content` работает здесь плохо (собственно, он почти всегда работает не так, как хотят студенты).
Что он делает? Создает колонку по минимальному контенту: то есть, по самому длинному слову. А это значит, что если слов хотя бы 2, то у нас всегда будет 2 строки.

Рекомендую использовать `auto` для текста и `1fr` для поля. Так текст займет размер по ширине, а поле — все остальное пространство.
Для поля стоит задать минимальную ширину, чтобы при переполнении текст не ужал его в ноль.

2023-01-16 23:03 UTC, wrgraff commented on source/form.html
> +          <label class="form-comment__title" for="comment">Комментарий</label>
А почему лейбл переместился под поле?

2023-01-16 23:03 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +  }
Вот у этой обертки должно быть ограничение ширины, а то получается, что плашка не по контенту стоит, а от левого края:
<img width="1594" alt="изображение" src="https://user-images.githubusercontent.com/37917037/212777553-48986dd0-b178-4f08-86b3-fe7a926420a1.png">

2023-01-16 23:03 UTC, wrgraff commented on source/sass/blocks/form-options.scss
> +@media (min-width: $tablet-width) {
2 раза `$tablet-width`

2023-01-18 11:22 UTC, wrgraff approved these changes

2023-01-18 11:22 UTC, merged